version: '3.9'

services:
  tempocerto-front:
    container_name: tempocerto-front
    build:
      context: ./
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
    - ../:/app
    ports:
    - 3000:3000
    networks: 
      - tempocerto-bridge

networks:
  tempocerto-bridge:
    driver: bridge